In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4]

In [3]:
type(mylist)

list

In [4]:
arr_vec = np.array(mylist)
arr_mat = arr_vec.reshape(-1, 1)

In [5]:
print(type(arr_vec), type(arr_mat))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
print('Vector Shape:', arr_vec.shape, 'Matrix Shape:', arr_mat.shape)

Vector Shape: (4,) Matrix Shape: (4, 1)


In [7]:
print('Vector dim:', arr_vec.ndim, 'Matrix dim:', arr_mat.ndim)

Vector dim: 1 Matrix dim: 2


In [8]:
arr1 = np.arange(20,10,-.5)
arr1

array([20. , 19.5, 19. , 18.5, 18. , 17.5, 17. , 16.5, 16. , 15.5, 15. ,
       14.5, 14. , 13.5, 13. , 12.5, 12. , 11.5, 11. , 10.5])

In [9]:
arr1.ndim

1

In [10]:
zeros_arr_vec = np.zeros(5)
zeros_arr_mat = np.zeros((5,1))
print('Zero Vector Shape:', zeros_arr_vec.shape, 'Zeros Matrix Shape:', zeros_arr_mat.shape)

Zero Vector Shape: (5,) Zeros Matrix Shape: (5, 1)


In [11]:
# arr0 = np.arange(0,4).reshape(-1,1)
arr0 = np.arange(0,4)
# print(arr0.shape)
aa = arr_vec + arr0
print('arr0',arr0.shape,'aa', aa.shape)

arr0 (4,) aa (4,)


In [12]:
arr1 = np.arange(0,4).reshape(1,-1)
aa = arr_vec + arr1
print('arr1',arr1.shape,'aa', aa.shape)

arr1 (1, 4) aa (1, 4)


In [13]:
arr1 = np.arange(0,4).reshape(-1,1)
print(arr1.shape)
aa = arr_vec + arr1
print('arr1',arr1.shape,'aa', aa.shape)
print(aa)

(4, 1)
arr1 (4, 1) aa (4, 4)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [14]:
arr_vec2 = np.array([2,3,4,5, 6])
arr_mat2 = arr_vec2.reshape(-1, 1)
aa = arr_vec + arr_mat2
print('arr_mat2', arr_mat2.shape,'arr_vec', arr_vec.shape,'aa', aa.shape)
print(aa)

arr_mat2 (5, 1) arr_vec (4,) aa (5, 4)
[[ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [15]:
arr_vec2 = np.array([1,2,3,4,5,6,7,8])
arr_mat2 = arr_vec2.reshape(2, 4)
aa = arr_vec + arr_mat2
print('arr_mat2', arr_mat2.shape,'arr_vec', arr_vec.shape,'aa', aa.shape)
print('arr_mat2', arr_mat2,'arr_vec', arr_vec,'aa', aa, sep = '\n')

arr_mat2 (2, 4) arr_vec (4,) aa (2, 4)
arr_mat2
[[1 2 3 4]
 [5 6 7 8]]
arr_vec
[1 2 3 4]
aa
[[ 2  4  6  8]
 [ 6  8 10 12]]


In [16]:
# arr_vec2 = np.array([1,2,3,4,5,6,7,8])
# arr_mat2 = arr_vec2.reshape(4,2)
# aa = arr_vec + arr_mat2
# print('arr_mat2', arr_mat2.shape,'arr_vec', arr_vec.shape,'aa', aa.shape)
# print('arr_mat2', arr_mat2,'arr_vec', arr_vec,'aa', aa, sep = '\n')

In [17]:
# arr_vec2 = np.array([1,2,3,4,5,6,7,8])
# arr_mat2 = arr_vec2.reshape(1,-1)
# print('arr_mat2', arr_mat2.shape)
# print('arr_vec', arr_vec.shape)
# aa = arr_vec + arr_mat2

# print('arr_mat2', arr_mat2,'arr_vec', arr_vec,'aa', aa, sep = '\n')

In [18]:
arr_vec2 = np.array([1,2,3,4])
arr_mat2 = arr_vec2.reshape(4,1)
arr_mat3 = arr_vec2.reshape(1,4)
print('arr_mat2', arr_mat2.shape)
print('arr_mat3', arr_mat3.shape)

aa = arr_mat3 + arr_mat2

print('aa', aa.shape)
print('aa', aa)

arr_mat2 (4, 1)
arr_mat3 (1, 4)
aa (4, 4)
aa [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [19]:
arr_vec2 = np.array([1,2,3,4])
arr_vec3 = np.array([1,2,3,4,5])

arr_mat2 = arr_vec2.reshape(1,4)
arr_mat3 = arr_vec3.reshape(5,1)
print('arr_mat2', arr_mat2.shape)
print('arr_mat3', arr_mat3.shape)

aa = arr_mat3 + arr_mat2

print('aa', aa.shape)
print('aa', aa)

arr_mat2 (1, 4)
arr_mat3 (5, 1)
aa (5, 4)
aa [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [20]:
# arr_vec2 = np.array([1,2,3,4])
# arr_vec3 = np.array([1,2,3,4,5])

# arr_mat2 = arr_vec2.reshape(1,4)
# arr_mat3 = arr_vec3.reshape(1,5)
# print('arr_mat2', arr_mat2.shape)
# print('arr_mat3', arr_mat3.shape)

# aa = arr_mat3 + arr_mat2

# print('aa', aa.shape)
# print('aa', aa)

In [21]:
# arr_vec2 = np.array([1,2,3,4])
# arr_vec3 = np.array([1,2,3,4,5,6,7,8])

# arr_mat2 = arr_vec2.reshape(1,4)
# arr_mat3 = arr_vec3.reshape(4,2)
# print('arr_mat2', arr_mat2.shape)
# print('arr_mat3', arr_mat3.shape)

# aa = arr_mat3 + arr_mat2

# print('aa', aa.shape)
# print('aa', aa)

In [22]:
arr_vec2 = np.array([1,2,3,4])
arr_vec3 = np.array([1,2,3,4,5,6,7,8])

arr_mat2 = arr_vec2.reshape(1,4)
arr_mat3 = arr_vec3.reshape(2,4)
print('arr_mat2', arr_mat2.shape)
print('arr_mat3', arr_mat3.shape)

aa = arr_mat3 + arr_mat2

print('aa', aa.shape)
print('aa', aa)

arr_mat2 (1, 4)
arr_mat3 (2, 4)
aa (2, 4)
aa [[ 2  4  6  8]
 [ 6  8 10 12]]


In [23]:
arr_vec2 = np.array([1,2])
arr_vec3 = np.array([1,2,3,4,5,6,7,8])

arr_mat2 = arr_vec2.reshape(2,1)
arr_mat3 = arr_vec3.reshape(1,2,4)
print('arr_mat2 shape', arr_mat2.shape)
print('arr_mat2', arr_mat2)

print('arr_mat3 shape', arr_mat3.shape)
print('arr_mat3', arr_mat3)
aa = arr_mat3 + arr_mat2

print('aa', aa.shape)
print('aa', aa)

arr_mat2 shape (2, 1)
arr_mat2 [[1]
 [2]]
arr_mat3 shape (1, 2, 4)
arr_mat3 [[[1 2 3 4]
  [5 6 7 8]]]
aa (1, 2, 4)
aa [[[ 2  3  4  5]
  [ 7  8  9 10]]]


In [24]:
arr = np.linspace(0,10,20)
arr.shape

(20,)

In [25]:
np.random.rand(4,2).shape

(4, 2)

In [26]:
np.random.rand(4,1).shape

(4, 1)

In [27]:
np.random.rand(4).shape


(4,)

In [28]:
np.random.randn(4,2).shape

(4, 2)

In [29]:
np.random.normal(5,2,(4,2)).shape

(4, 2)

In [30]:
a = np.random.normal(5,2,(4,2))

In [31]:
np.random.randint(1,15,10).shape

(10,)

In [32]:
np.random.randint(1,5,10)

array([1, 4, 4, 3, 3, 4, 2, 1, 3, 1])

In [33]:
np.random.seed(421)

In [34]:
a1 = a.max()
a2 = np.max(a)
print(a1,a2)

9.962049602660008 9.962049602660008


In [35]:
a1 = a.max(axis=0)
a2 = np.max(a,axis=0)
print(a1,a2)

[9.9620496  4.30368086] [9.9620496  4.30368086]


In [36]:
a1 = a.argmax()
a2 = np.argmax(a)
print(a1,a2)

0 0


In [37]:
a1 = a.argmax(axis=0)
a2 = np.argmax(a,axis=0).shape
print(a1,a2)

[0 3] (2,)


In [38]:
arr1 = np.arange(0,5)
arr2 = np.arange(0,5,.5)

In [43]:
arr3 = arr2[arr2>2.1]
arr3

array([2.5, 3. , 3.5, 4. , 4.5])

In [45]:
1/(arr1-2)

c:\Users\mm\anaconda3\envs\pytorchenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-0.5, -1. ,  inf,  1. ,  0.5])