In [104]:
import torch
import numpy as np

In [105]:
torch.__version__

'1.12.1'

In [106]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [107]:
print(type(arr), arr.dtype)

<class 'numpy.ndarray'> int32


In [108]:
x1 = torch.from_numpy(arr)
print(type(x1), x1.dtype)

<class 'torch.Tensor'> torch.int32


In [109]:
x2 = torch.as_tensor(arr)
print(type(x2), x2.dtype)

<class 'torch.Tensor'> torch.int32


In [110]:
x3 = torch.tensor(arr)
print(type(x3), x3.dtype)

<class 'torch.Tensor'> torch.int32


In [111]:
x4 = torch.Tensor(arr)
print(type(x4), x4.dtype)

<class 'torch.Tensor'> torch.float32


In [112]:
arr[0]=100
print(arr)
print(x1)
print(x2)
print(x3)
print(x4)

[100   2   3]
tensor([100,   2,   3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


In [113]:
a = torch.empty(4,2)

In [114]:
b = torch.zeros(4,3)
b.dtype

torch.float32

In [115]:
b2 = torch.zeros(4,3, dtype=torch.int32)
b2.dtype

torch.int32

In [116]:
c = torch.ones(4,2)
c

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [117]:
d = torch.tensor([1, 2, 3])
d

tensor([1, 2, 3])

In [118]:
f = torch.Tensor([1, 2, 3])
f

tensor([1., 2., 3.])

In [119]:
x = torch.arange(0,6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [120]:
y = x[:,1]
y.shape

torch.Size([3])

In [121]:
y = x[:,:-1]
y.shape

torch.Size([3, 1])

In [122]:
x = torch.arange(0,6)

In [123]:
yv = x.view(2,3)

In [124]:
yr= x.reshape(2,3)

In [125]:
yc = x.clone().reshape(2, 3)

In [126]:
x[0] = 100
print(x, yv, yr, yc, sep='\n')

tensor([100,   1,   2,   3,   4,   5])
tensor([[100,   1,   2],
        [  3,   4,   5]])
tensor([[100,   1,   2],
        [  3,   4,   5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [127]:
# y = torch.copy_(x)

In [133]:
yr.add_(yc)
print(yr, yc, sep='\n')

tensor([[100,   2,   4],
        [  6,   8,  10]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
yr.mul(yc) 

tensor([[ 0,  2,  8],
        [18, 32, 50]])

In [ ]:
# yr.mul(yc.T)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
x = torch.arange(0,6)

RuntimeError: tensor.mT is only supported on matrices or batches of matrices. Got 1-D tensor.

In [140]:
x

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
x.matmul(x)

AttributeError: 'Tensor' object has no attribute 'matmul_'

In [ ]:
yr.mm(yc.T)
print(yr, yc, sep='\n')


tensor([[ 10, 328],
        [ 28, 100]])

In [150]:
yr@yc.T
print(yr, yc, sep='\n')

tensor([[100,   2,   4],
        [  6,   8,  10]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [153]:
torch.manual_seed(42)
X3D = torch.rand(2,2,2)
X3D

tensor([[[0.8823, 0.9150],
         [0.3829, 0.9593]],

        [[0.3904, 0.6009],
         [0.2566, 0.7936]]])

In [154]:
torch.manual_seed(101)
Y3D = torch.rand(2,2,2)
Y3D

tensor([[[0.1980, 0.4503],
         [0.0909, 0.8872]],

        [[0.2894, 0.0186],
         [0.9095, 0.3406]]])

In [156]:
Z3D = X3D.matmul(Y3D)
Z3D

tensor([[[0.2579, 1.2091],
         [0.1630, 1.0235]],

        [[0.6595, 0.2119],
         [0.7961, 0.2751]]])

In [157]:
Z3D = X3D@Y3D
Z3D

tensor([[[0.2579, 1.2091],
         [0.1630, 1.0235]],

        [[0.6595, 0.2119],
         [0.7961, 0.2751]]])

In [161]:
X3D.norm(keepdim=True)

tensor([[[1.9727]]])

In [163]:
X3D.numel()

8

In [174]:
x = torch.rand(1, 4, 3, 1)
x

tensor([[[[0.1578],
          [0.7040],
          [0.0616]],

         [[0.3781],
          [0.5510],
          [0.7550]],

         [[0.8346],
          [0.0104],
          [0.2535]],

         [[0.4538],
          [0.5163],
          [0.6199]]]])

In [172]:
len(x)

1

In [178]:
x.ndim

4